image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Upload'
          script:
            - zip -r 古文觀止.epub META-INF mimetype OEBPS
            - pipe: atlassian/bitbucket-upload-file:0.3.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: '*.epub'
